name: seqtk_subseq
namespace: seqtk
description: 
keywords: [tag1, tag2]
links:
  repository: https://github.com/lh3/seqtk/tree/v1.4
license: MIT

argument_groups:
  - name: Inputs
    arguments:
      - name: --input
        type: file
        description: The input FASTA/Q file.
        required: true
      - name: "--regions_file"
        type: file
        description: |
          File with regions to extract. Can be either a list file 
          with one sequence name per line or a bed file.
        required: true

  - name: Outputs
    arguments:
      - name: --output
        type: file
        description: The output FASTA/Q file.
        required: true
        direction: output

  - name: Options
    arguments:
      - name: "--tab"
        type: boolean
        description: Output in tab-delimited format.
        default: false
      - name: "--strand_aware"
        type: boolean
        description: Strand-aware mode.
        default: false
      - name: "--line_length"
        type: integer
        description: Number of bases per line.
        default: 60

resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: ../test_data

engines:
  - type: docker
    image: quay.io/biocontainers/seqtk:1.4--he4a0461_2
runners:
  - type: executable
  - type: nextflow