name: fastqc
namespace: fastqc
description: FastQC - A high throughput sequence QC analysis tool.
keywords: [Quality control, BAM, SAM, FASTQ]
links:
  repository: https://github.com/s-andrews/FastQC
license: GPL-3.0, Apache-2.0
authors:
  - __merge__: /src/_authors/theodoro_gasperin.yaml
    roles: [ author, maintainer ]

argument_groups:
  - name: Inputs
    arguments:
      - name: --input
        type: file
        direction: input
        multiple: true
        multiple_sep: ","
        description: FASTQ file(s) to be analyzed.
        required: true
        example: input.fq
        
  - name: Outputs
    arguments:
      - name: --html
        type: file
        direction: output
        multiple: true
        multiple_sep: ","
        description: |
          Create an HTML report of the results.
        example: input_fastqc.html
      
      - name: --zip
        type: file
        direction: output
        multiple_sep: ","
        description: |
          Create the zip file(s) containing: html report, data, images, icons etc.
        example: input_fastqc.zip
      
      - name: --outdir
        alternatives: -o
        type: file
        direction: output
        description: |
          Create the output files in the specified directory.
        example: output_dir

  - name: Options
    arguments:  
      - name: --casava
        type: boolean_true
        description: Files come from raw casava output.
      
      - name: --nano
        type: boolean_true
        description: Files come from nanopore sequences and are in fast5 format.
      
      - name: --nofilter
        type: boolean_true
        description: |
          If running with --casava then don't remove read flagged by
          casava as poor quality when performing the QC analysis.
      
      - name: --extract
        type: boolean_true
        description: |
          If set then the zipped output file will be uncompressed in
          the same directory after it has been created.  By default
          this option will be set if fastqc is run in non-interactive
          mode.

      - name: --java
        alternatives: -j
        type: file
        description: |
          Provides the full path to the java binary you want to use to
          launch fastqc. If not supplied then java is assumed to be in
          your path.
        example: file
     
      - name: --noextract
        type: boolean_true
        description: |
          Do not uncompress the output file after creating it. 
          You should set this option if you do not wish to uncompress 
          the output when running in non-interactive mode.

      - name: --nogroup
        type: boolean_true
        description: |
          Disable grouping of bases for reads >50bp. 
          All reports will show data for every base in the read. 
          WARNING: Using this option will cause fastqc to crash 
          and burn if you use it on really long reads, and your 
          plots may end up a ridiculous size. You have been warned!

      - name: --min_length
        type: integer
        description: |
          Sets an artificial lower limit on the length of the 
          sequence to be shown in the report. As long as you 
          set this to a value greater or equal to your longest 
          read length then this will be the sequence length used 
          to create your read groups. This can be useful for making
          directly comparable statistics from datasets with somewhat 
          variable read lengths.
        example: 0

      - name: --format
        alternatives: -f
        type: string
        description: |
          Bypasses the normal sequence file format detection and 
          forces the program to use the specified format. 
          Valid formats are bam, sam, bam_mapped, sam_mapped, and fastq.
        example: bam

      - name: --threads
        alternatives: -t
        type: integer
        description: |
          Specifies the number of files which can be processed simultaneously. 
          Each thread will be allocated 250MB of memory so you shouldn't 
          run more threads than your available memory will cope with, 
          and not more than 6 threads on a 32-bit machine.
        example: 4
        
      - name: --contaminants
        alternatives: -c
        type: file
        description: |
          Specifies a non-default file which contains the list 
          of contaminants to screen overrepresented sequences against. 
          The file must contain sets of named contaminants in the form
          name[tab]sequence. Lines prefixed with a hash will be ignored.
        example: contaminants.txt
        
      - name: --adapters
        alternatives: -a
        type: file
        description: |
          Specifies a non-default file which contains the list of 
          adapter sequences which will be explicitly searched against 
          the library. The file must contain sets of named adapters 
          in the form name[tab]sequence. Lines prefixed with a hash will be ignored.
        example: adapters.txt

      - name: --limits
        alternatives: -l
        type: file
        description: |
          Specifies a non-default file which contains 
          a set of criteria which will be used to determine 
          the warn/error limits for the various modules. 
          This file can also be used to selectively remove 
          some modules from the output altogether. The format 
          needs to mirror the default limits.txt file found in 
          the Configuration folder.
        example: limits.txt

      - name: --kmers
        alternatives: -k
        type: integer
        description: |
          Specifies the length of Kmer to look for in the Kmer 
          content module. Specified Kmer length must be between 
          2 and 10. Default length is 7 if not specified.
        example: 7
        
      - name: --quiet
        alternatives: -q
        type: boolean_true
        description: |
          Suppress all progress messages on stdout and only report errors.

      - name: --dir
        alternatives: -d
        type: file
        description: |
          Selects a directory to be used for temporary 
          files written when generating report images. 
          Defaults to system temp directory if not specified.
        example: temp_dir

        

resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh

engines:
  - type: docker
    image: biocontainers/fastqc:v0.11.9_cv8
    setup:
      - type: docker
        run: |
          fastqc --version > /var/software_versions.txt

runners:
  - type: executable
  - type: nextflow