name: seqtk
description: |
  Seqtk is a fast and lightweight tool for processing sequences in the FASTA or FASTQ format. 
  It seamlessly parses both FASTA and FASTQ files which 
  can also be optionally compressed by gzip. 
  "Sample"
keywords: [tag1, tag2]
links:
  repository: https://github.com/lh3/seqtk/tree/master
license: MIT
argument_groups:
  - name: Inputs
    arguments:
      - name: --input
        type: file
        description: The input FASTA/Q file.
        required: true
        example: read.fq
  - name: Outputs
    arguments:
      - name: --output
        type: file
        description: The output FASTA/Q file.
        required: true
        direction: output
        example: sub.fq
  - name: Options
    arguments:
      - name: --seed
        alternatives: -s
        type: integer
        description: Seed for random generator.
        example: 42
      - name: --fraction_number
        type: double
        description: Fraction or number of sequences to sample.
        required: true
        example: 0.1
      - name: --two_pass_mode
        alternatives: -2
        type: boolean
        description: Twice as slow but with much reduced memory
        default: false
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/seqtk:1.4--he4a0461_2
    setup:
      - type: docker
        run: |
          touch ./var/software_versions.txt && \
          # version=$(seqtk 2>&1 | grep "Version:" | awk '{print $2}') && \
          version=$(docker run quay.io/biocontainers/seqtk:1.4--he4a0461_2 seqtk 2>&1 | grep "Version:" | awk '{print $2}') && \
          echo "seqtk: $version" > ./var/software_versions.txt
runners:
  - type: executable
  - type: nextflow