name: bedtools_genomecov
namespace: bedtools
description: |
  Compute the coverage of a feature file among a genome.
keywords: [genome coverage, BED]
links:
  documentation: https://bedtools.readthedocs.io/en/latest/content/tools/genomecov.html
  repository: https://github.com/arq5x/bedtools2
references:
  doi: 10.1093/bioinformatics/btq033
license: GPL-2.0, MIT
requirements:
  commands: [bedtools]
authors:
  - __merge__: /src/_authors/theodoro_gasperin.yaml
    roles: [ author, maintainer ]

argument_groups:
  - name: Inputs
    arguments:
      - name: --input
        alternatives: -i
        type: file
        direction: input
        description: |
          The input file (BED/GFF/VCF) to be used.
        required: true
        example: input.bed

      - name: --genome
        alternatives: -g
        type: file
        direction: input
        description: |
          The genome file to be used.
        required: true
        example: genome.txt
    
  - name: Outputs
    arguments:
      - name: --output
        type: file
        direction: output
        description: | 
          The output BED file. 
        required: true
        example: output.bed
  
  - name: Options
    arguments:
      - name: --input_bam
        alternatives: -ibam
        type: boolean_true
        description: |
          The input file is in BAM format.
          Note: BAM _must_ be sorted by position
      

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh

engines:
  - type: docker
    image: debian:stable-slim
    setup:
      - type: apt
        packages: [bedtools, procps]
      - type: docker
        run: |
          echo "bedtools: \"$(bedtools --version | sed -n 's/^bedtools //p')\"" > /var/software_versions.txt

runners:
  - type: executable
  - type: nextflow