name: agat_sp_add_intergenic_regions
namespace: agat
description: |
    The script aims to add intergenic features (intergenic_region) to gtf/gff file. The intergenic regions are deduced from gene features (feature type gene from the 3rd column).
keywords: [gene annotations, intergenic regions]
links:
  homepage: https://github.com/NBISweden/AGAT
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_add_intergenic_regions.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references: 
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  - commands: [agat]
authors:
  - __merge__: /src/_authors/leila_paquay.yaml
    roles: [ author, maintainer ]
argument_groups:
  - name: Inputs
    arguments:
      - name: --gff
        alternatives: [-f, --ref]
        description: Input GTF/GFF file.
        type: file
        required: true
        direction: input
        example: input.gff
  - name: Outputs
    arguments:
      - name: --output
        alternatives: [--out, -o]
        description: Output file (default GFF3 - see config to modify output format).
        type: file
        direction: output
        required: true
        example: output.gff
  - name: Arguments
    arguments:
      - name: --config
        alternatives: [-c]
        description: |
          AGAT config file. By default AGAT takes the original agat_config.yaml shipped with AGAT. The `--config` option gives you the possibility to use your own AGAT config file (located elsewhere or named differently).        
        type: file
        required: false
        example: custom_agat_config.yaml
      - name: --verbose
        alternatives: [-v]
        description: Add verbosity.
        type: boolean_true
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/agat:1.4.0--pl5321hdfd78af_0
    setup:
      - type: docker
        run: |
          agat --version | sed 's/AGAT\s\(.*\)/agat: "\1"/' > /var/software_versions.txt
runners:
  - type: executable
  - type: nextflow