name: agat_sp_add_start_and_stop
namespace: agat
description: |
  The script adds start and stop codons when a CDS feature exists. The
  script looks at the nucleotide sequence and checks the presence of start
  and stop codons. The script works even if the start or stop codon are
  split over several CDS features.
keywords: [gene annotations]
links:
  homepage: https://github.com/NBISweden/AGAT
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_add_start_and_stop.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references: 
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
authors:
  - __merge__: /src/_authors/leila_paquay.yaml
    roles: [ author, maintainer ]
argument_groups:
  - name: Inputs
    arguments:
      - name: --gff
        alternatives: [-i, -g]
        description: Input GTF/GFF file.
        type: file
        required: true
        direction: input
        example: input.gff
      - name: --fasta
        alternatives: [--fa, -f]
        description: Input fasta file. Needed to check that CDS sequences start by start codon and stop by stop codon.
        type: file
        required: true
        direction: input
        example: input.fasta
  - name: Outputs
    arguments:
      - name: --output
        alternatives: [--out, -o]
        description: Output gff file updated.
        type: file
        direction: output
        required: true
        example: output.gff
  - name: Arguments
    arguments:
      - name: --ct
        alternatives: [--codon, --table]
        description: Codon table to use. [default 1]
        type: integer
        required: false
        example: 1
      - name: --extend
        alternatives: [-e]
        description: When no start/stop codon found, try to extend the CDS to meet the next start/stop codon in the sequence.
        type: boolean_true
      - name: --ni
        alternatives: [--na]
        description: no iupac / no ambiguous, avoid usage of IUPAC. By default IUPAC is used that means, NNN is seen as start and/or stop codon.
        type: boolean_true
      - name: --verbose
        alternatives: [-v]
        description: Verbose for debugging purpose.
        type: boolean_true
      - name: --config
        alternatives: [-c]
        description: |
          Input agat config file. By default AGAT takes as input agat_config.yaml file from the working directory if any, otherwise it takes the original agat_config.yaml shipped with AGAT. To get the agat_config.yaml locally type: `agat config --expose`. The `--config` option gives you the possibility to use your own AGAT config file (located elsewhere or named differently).
        type: file
        required: false
        example: custom_agat_config.yaml
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/agat:1.4.0--pl5321hdfd78af_0
    setup:
      - type: docker
        run: |
          agat --version | sed 's/AGAT\s\(.*\)/agat: "\1"/' > /var/software_versions.txt
runners:
  - type: executable
  - type: nextflow