name: agat_sp_prokka_infer_name_from_attributes
namespace: agat
description: |
  The script aims to fill a Name attribute based on <gene> attribute in a
  prokka gff annotation file. If no gene attribute is present it take if
  from the <inference> attribute.
keywords: [gene annotations, GFF conversion, prokka]
links:
  homepage: https://github.com/NBISweden/AGAT
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_Prokka_inferNameFromAttributes.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references: 
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  - commands: [agat]
authors:
  - __merge__: /src/_authors/leila_paquay.yaml
    roles: [ author, maintainer ]
argument_groups:
  - name: Inputs
    arguments:
      - name: --gff
        alternatives: [-f]
        description: Input GTF/GFF file.
        type: file
        required: true
        direction: input
        example: input.gff
  - name: Outputs
    arguments:
      - name: --output
        alternatives: [-o, --out, --outfile]
        description: Output GFF file.
        type: file
        direction: output
        required: true
        example: output.gff
  - name: Arguments
    arguments:
      - name: --force
        description: |
          If Name attribute already exists, they will be replaced if a new one is found.
        type: boolean_true
      - name: --config
        alternatives: [-c]
        description: |
          AGAT config file. By default AGAT takes the original agat_config.yaml shipped with AGAT. The `--config` option gives you the possibility to use your own AGAT config file (located elsewhere or named differently).
        type: file
        required: false
        example: custom_agat_config.yaml
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/agat:1.4.0--pl5321hdfd78af_0
    setup:
      - type: docker
        run: |
          agat --version | sed 's/AGAT\s\(.*\)/agat: "\1"/' > /var/software_versions.txt
runners:
  - type: executable
  - type: nextflow