name: samtools_index
namespace: samtools
description: Index BAM files
keywords: [stats, mapping, counts, chromosome, bam, sam, cram]
links:
  homepage: https://www.htslib.org/
  documentation: https://www.htslib.org/doc/samtools-index.html
  repository: https://github.com/samtools/samtools.git
references: 
  doi: 10.1093/bioinformatics/btp352, 10.1093/gigascience/giab008
license: MIT/Expat

argument_groups:
  - name: Inputs
    arguments:
      - name: --bam
        alternatives: -b
        type: file
        description: BAM input file.
      - name: "--bam_csi_index"
        type: boolean
        description: Create a CSI index for BAM files instead of the traditional BAI index. This will be required for genomes with larger chromosome sizes.
  - name: Outputs
    arguments:
      - name: --output_bai
        alternatives: [ -o, --output ]
        type: file
        description: BAM index
        direction: output
        required: true
        must_exist: false
        example: out.bam.bai
        must_exist: false
      - name: --output_csi
        alternatives: [ -c, --csi ]
        type: file
        description: CSI index
        direction: output
        default: out.bam.csi
      - name: --min-shift
        alternatives: -m
        type: integer
        description: Create a CSI index, with a minimum interval size of 2^INT.
        default: 0
  - name: Options
    arguments:
      - name: --individual
        alternatives: -M
        type: integer
        description: |
          Interpret all filename arguments as alignment files to
          be indexed individually. (Without -M, filename arguments
          are interpreted solely as per the second synopsis.)


   
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/samtools:1.19.2--h50ea8bc_1
    setup:
      - type: docker
        run: |
          echo "$(samtools --version 2>&1)" > /var/software_versions.txt
runners:
- type: executable
- type: nextflow