name: agat_sp_alignment_output_style
namespace: agat
description: |
  The script takes a normal gtf/gff annotation format file and convert it
  to gff3 alignment format. It means it add a structure of match /
  match_part as relationship between the different features.
keywords: [gene annotations, GFF conversion]
links:
  homepage: https://github.com/NBISweden/AGAT
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_alignment_output_style.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references: 
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
authors:
  - __merge__: /src/_authors/leila_paquay.yaml
    roles: [ author, maintainer ]
argument_groups:
  - name: Inputs
    arguments:
      - name: --gff
        alternatives: [-g, -ref]
        description: Input GTF/GFF file.
        type: file
        required: true
        direction: input
        example: input.gff
  - name: Outputs
    arguments:
      - name: --output
        alternatives: [-o]
        description: Output GFF file.
        type: file
        direction: output
        required: true
        example: output.gff
  - name: Arguments
    arguments:
      - name: --verbose
        alternatives: [-v]
        description: Verbose option to see the warning messages when parsing the gff file.
        type: boolean_true
        required: false
      - name: --config
        alternatives: [-c]
        description: |
          Input agat config file. By default AGAT takes as input agat_config.yaml file from the working directory if any, otherwise it takes the orignal agat_config.yaml shipped with AGAT. To get the agat_config.yaml locally type: `agat config --expose`. The `--config` option gives you the possibility to use your own AGAT config file (located elsewhere or named differently).
        type: file
        required: false
        example: custom_agat_config.yaml
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/agat:1.4.0--pl5321hdfd78af_0
    setup:
      - type: docker
        run: |
          agat --version | sed 's/AGAT\s\(.*\)/agat: "\1"/' > /var/software_versions.txt
runners:
  - type: executable
  - type: nextflow