name: nanoplot
description: |
  Run NanoPlot on nanopore-sequenced reads.
  "Sample"
keywords: ["quality control", "qc", "fastq", "sequencing summary", "nanopore"]
links:
  repository: https://github.com/wdecoster/NanoPlot/tree/master
  homepage: http://nanoplot.bioinf.be/
license: MIT
argument_groups:
  - name: Inputs
    arguments:
      - name: --fastq
        type: file
        description: List of input basecalled-FastQ files.
        example: read.fq
        multiple: true
      - name: --fasta
        type: file
        description: List of input Fasta files.
        example: read.fa
        multiple: true
      - name: --bam
        type: file
        description: BAM files.
        example: read.bam
        multiple: true
  - name: Outputs
    arguments:
      - name: --summary
        type: file
        description: A statistical summary
        direction: output
      - name: --plots
        type: file
        description: A number of plots
        direction: output
        example: report.png
      - name: --html
        type: file
        description: Plots generated by NanoPlot
        direction: output
        example: plots.png
      - name: --txt
        type: file
        description: Stats from NanoPlot
        direction: output
        example: stats.txt
      - name: --log
        type: file
        description: log file of NanoPlot run
        direction: output
        example: run.log
      - name: --versions
        type: file
        description: File containing software versions
        direction: output
        example: versions.yml
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/nanoplot:0.16.2--py35_0
    setup:
      - type: docker
        run: |
          touch ./var/software_versions.txt && \
          # version=$(NanoPlot --version) && \
          version=$(docker run quay.io/biocontainers/nanoplot:0.16.2--py35_0 NanoPlot --version) && \
          echo "$version" > ./var/software_versions.txt
runners:
  - type: executable
  - type: nextflow