name: nanoplot
description: |
  Run NanoPlot on nanopore-sequenced reads.
keywords: ["quality control", "qc", "fastq", "sequencing summary", "nanopore"]
links:
  repository: https://github.com/wdecoster/NanoPlot
  homepage: http://nanoplot.bioinf.be/
  documentation: https://nanoplot.bioinf.be/
references:
  doi: 10.1093/bioinformatics/btad311
license: MIT
argument_groups:
  - name: Inputs
    arguments:
      - name: --fastq
        type: file
        description: List of input basecalled-FastQ files.
        example: read.fq
        multiple: true
      - name: --summary
        type: file
        description: Summary files.
        example: read.txt
        multiple: true
      - name: --bam
        type: file
        description: BAM files.
        example: read.bam
        multiple: true
  - name: Outputs
    arguments:
      - name: --txt
        type: file
        description: Stats from NanoPlot
        direction: output
        example: NanoStats.txt
      - name: --png
        type: file
        description: Plots generated by NanoPlot
        direction: output
        example: plots.png
      - name: --html
        type: file
        description: NanoPlot report
        direction: output
        example: report.html
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/nanoplot:1.42.0--pyhdfd78af_0
    setup:
      - type: docker
        run: |
          touch ./var/software_versions.txt && \
          version=$(NanoPlot --version) && \
          # version=$(docker run quay.io/biocontainers/nanoplot:1.42.0--pyhdfd78af_0 NanoPlot --version) && \
          echo "$version" > ./var/software_versions.txt
runners:
  - type: executable
  - type: nextflow