name: bedtools_groupby
namespace: bedtools
description: |
  
keywords: [feature intersection, BAM, BED, GFF, VCF]
links:
  documentation: https://bedtools.readthedocs.io/en/latest/content/tools/groupby.html
  repository: https://github.com/arq5x/bedtools2
references:
  doi: 10.1093/bioinformatics/btq033
license: GPL-2.0, MIT
requirements:
  commands: [bedtools]
authors:
  - __merge__: /src/_authors/theodoro_gasperin.yaml
    roles: [ author, maintainer ]

argument_groups:
  - name: Inputs
    arguments:
      - name: --input
        alternatives: -i
        type: file
        direction: input
        description: |
          The input BED file to be used.
        required: true
        example: input_a.bed
        
  - name: Outputs
    arguments:
      - name: --output
        type: file
        direction: output
        description: | 
          The output groupby BED file. 
        required: true
        example: output.bed
  
  - name: Options
    arguments:
      - name: --groupby
        alternatives: -g
        type: string
        description: |
          Specify the columns (1-based) for the grouping.
          The columns must be comma separated.
          - Default: 1,2,3   

      # - name: --groupby
      #   alternatives: -g
      #   type: string
      #   description: |
      #     Specify the columns (1-based) for the grouping.
      #     The columns must be comma separated.
      #     - Default: 1,2,3     

resources:
  - type: bash_script
    path: script.sh

test_resources:
  - type: bash_script
    path: test.sh

engines:
  - type: docker
    image: debian:stable-slim
    setup:
      - type: apt
        packages: [bedtools, procps]
      - type: docker
        run: |
          echo "bedtools: \"$(bedtools --version | sed -n 's/^bedtools //p')\"" > /var/software_versions.txt

runners:
  - type: executable
  - type: nextflow
