name: busco_download_datasets
namespace: busco
description: Downloads available busco datasets
keywords: [lineage datasets]
links:
  homepage: https://busco.ezlab.org/
  documentation: https://busco.ezlab.org/busco_userguide.html
  repository: https://gitlab.com/ezlab/busco
references:
  doi: 10.1007/978-1-4939-9173-0_14
license: MIT
authors:
  - __merge__: /src/_authors/dorien_roosen.yaml
    roles: [ author, maintainer ]
argument_groups:
  - name: Inputs
    arguments:
      - name: --download
        type: string
        description: |
          Download dataset. Possible values are a specific dataset name, "all", "prokaryota", "eukaryota", or "virus".
          The full list of available datasets can be viewed [here](https://busco-data.ezlab.org/v5/data/lineages/) or by running the busco/busco_list_datasets component.
        required: true
        example: stramenopiles_odb10
  - name: Outputs
    arguments:
      - name: --download_path
        direction: output
        type: file
        description: |
          Local filepath for storing BUSCO dataset downloads
        required: false
        default: busco_downloads
        example: busco_downloads
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
engines:
  - type: docker
    image: quay.io/biocontainers/busco:5.7.1--pyhdfd78af_0
    setup:
      - type: docker
        run: |
          busco --version | sed 's/BUSCO\s\(.*\)/busco: "\1"/' > /var/software_versions.txt
runners:
  - type: executable
  - type: nextflow
