name: snpeff
description: |
  Genetic variant annotation, and functional effect prediction toolbox. 
  It annotates and predicts the effects of genetic variants on genes and 
  proteins (such as amino acid changes).
keywords: ["dna polymorphism", "genetic variation", "snp analysis", "next-generation dna sequencing"]
links:
  repository: https://github.com/pcingola/SnpEff
  homepage: https://pcingola.github.io/SnpEff/
  documentation: https://pcingola.github.io/SnpEff/
references:
  doi: 10.3389/fgene.2012.00035
license: MIT
argument_groups:
  - name: Inputs
    arguments:
      - name: -input
        type: file
        description: Input variants file.
        example: test.vcf
        direction: input
        required: true
      - name: -genome_version
        type: string
        description: Reference genome version.
        example: GRCh37.75
        direction: input
        required: true
  - name: Outputs
    arguments:
      - name: --output
        type: file
        description: The output file.
        example: out.vcf
        direction: output
  - name: Options
    arguments:
      - name: -chr
        type: string
        description: |
          Prepend 'string' to chromosome name (e.g. 'chr1' instead of '1'). Only on TXT output.
      - name: -classic
        type: boolean_true
        description: Use old style annotations instead of Sequence Ontology and Hgvs.
      - name: -csvStats
        type: file
        description: Create CSV summary file.
      - name: -download
        type: boolean_true
        description: Download reference genome if not available.
      - name: -input_format
        alternatives: [-i]
        type: string
        description: Input format [ vcf, bed ]. Default: VCF.
      - name: -fileList
        type: boolean_true
        description: Input actually contains a list of files to process.
      - name: -output_format
        alternatives: [-o]
        type: string
        description: Ouput format [ vcf, gatk, bed, bedAnn ]. Default: VCF.
      - name: -stats
        alternatives: [-s, -htmlStats]
        type: boolean_true
        description: Create HTML summary file.
      - name: -noStats
        type: boolean_false
        description: Do not create stats (summary) file.
  - name: Results filter options
    arguments:
      - name: -fi
        alternatives: [-filterInterval]
        type: file
        description: |
          Only analyze changes that intersect with the intervals 
          specified in this file. This option can be used several times.
      - name: -no_downstream 
        type: boolean_false
        description: Do not show DOWNSTREAM changes
      - name: -no_intergenic
        type: boolean_false
        description: Do not show INTERGENIC changes.
      - name: -no_intron
        type: boolean_false
        description: Do not show INTRON changes.
      - name: -no_upstream
        type: boolean_false
        description: Do not show UPSTREAM changes.
      - name: -no_utr
        type: boolean_false
        description: Do not show 5_PRIME_UTR or 3_PRIME_UTR changes.
      - name: -no
        type: string
        description: |
          Do not show 'EffectType'. This option can be used several times.
  - name: Annotations options
    arguments:
      - name: -cancer 
        type: boolean_true
        description: Perform 'cancer' comparisons (Somatic vs Germline).
      - name: -cancerSamples
        type: file
        description: Two column TXT file defining 'original \t derived' samples.
      - name: -fastaProt
        type: file
        description: |
          Create an output file containing the resulting protein sequences.
      - name: -formatEff
        type: boolean_true
        description: |
          Use 'EFF' field compatible with older versions (instead of 'ANN').
      - name: -geneId
        type: boolean_true
        description: Use gene ID instead of gene name (VCF output).
      - name: -hgvs
        type: boolean_true
        description: Use HGVS annotations for amino acid sub-field.
      - name: -hgvsOld
        type: boolean_true
        description: Use old HGVS notation.
      - name: -hgvs1LetterAa 
        type: boolean_true
        description: Use one letter Amino acid codes in HGVS notation.
      - name: -hgvsTrId
        type: boolean_true
        description: Use transcript ID in HGVS notation.
      - name: -lof
        type: boolean_true
        description: |
          Add loss of function (LOF) and Nonsense mediated decay (NMD) tags.
      - name: -noHgvs
        type: boolean_false
        description: Do not add HGVS annotations.
      - name: -noLof
        type: boolean_false
        description: Do not add LOF and NMD annotations.
      - name: -noShiftHgvs
        type: boolean_false
        description: |
          Do not shift variants according to HGVS notation (most 3prime end).
      - name: -oicr
        type: boolean_true
        description: Add OICR tag in VCF file.
      - name: -sequenceOntology
        type: boolean_true
        description: Use Sequence Ontology terms.
  - name: Generic options
    arguments:
      - name: -config
        alternatives: [-c]
        type: file
        description: Specify config file
      - name: -configOption
        type: string
        description: Override a config file option (name=value).
      - name: -debug
        alternatives: [-d]
        type: boolean_true
        description: Debug mode (very verbose).
      - name: -dataDir
        type: file
        description: Override data_dir parameter from config file.
      # - name: -download
      #   type: boolean_true
      #   description: Download a SnpEff database, if not available locally.
      - name: -nodownload
        type: boolean_false
        description: Do not download a SnpEff database, if not available locally.
      - name: -noLog
        type: boolean_false
        description: Do not report usage statistics to server.
      - name: -quiet
        alternatives: [-q]
        type: boolean_true
        description: Quiet mode (do not show any messages or errors)
      - name: -verbose
        alternatives: [-v]
        type: boolean_true
        description: Verbose mode.
  - name: Database options
    arguments:
      - name: -canon 
        type: boolean_true
        description: Only use canonical transcripts.
      - name: -canonList
        type: file
        description: |
          Only use canonical transcripts, replace some transcripts using the 'gene_id         
          transcript_id' entries in <file>.
      - name: -tag
        type: string
        description: |
          Only use transcript having a tag 'tagName'. This option can be used multiple times.
      - name: -notag
        type: boolean_false
        description: |
          Filter out transcript having a tag 'tagName'. This option can be used multiple times.
      - name: -interaction
        type: boolean_true
        description: Annotate using interactions (requires interaction database).
      - name: -interval
        type: file
        description: |
          Use a custom intervals in TXT/BED/BigBed/VCF/GFF file (you may use this option many times).
      - name: -maxTSL
        type: integer
        description: Only use transcripts having Transcript Support Level lower than <TSL_number>.
      - name: -motif 
        type: boolean_true
        description: Annotate using motifs (requires Motif database).
      - name: -nextProt
        type: boolean_true
        description: Annotate using NextProt (requires NextProt database).
      - name: -noGenome
        type: boolean_false
        description: Do not load any genomic database (e.g. annotate using custom files).
      - name: -noExpandIUB
        type: boolean_false
        description: Disable IUB code expansion in input variants.
      - name: -noInteraction
        type: boolean_false
        description: Disable inteaction annotations.
      - name: -noMotif
        type: boolean_false
        description: Disable motif annotations.
      - name: -noNextProt
        type: boolean_false
        description: Disable NextProt annotations.
      - name: -onlyReg
        type: boolean_true
        description: Only use regulation tracks.
      - name: -onlyProtein
        type: boolean_true
        description: Only use protein coding transcripts.
      - name: -onlyTr
        type: file
        description: Only use the transcripts in this file. Format: One transcript ID per line.
        example: file.txt
      - name: -reg
        type: string
        description: Regulation track to use (this option can be used add several times).
      - name: -ss
        alternatives: [-spliceSiteSize]
        type: integer
        description: Set size for splice sites (donor and acceptor) in bases. Default: 2.
      - name: -spliceRegionExonSize
        type: integer
        description: Set size for splice site region within exons. Default: 3 bases.
      - name: -spliceRegionIntronMin
        type: integer
        description: |
          Set minimum number of bases for splice site region within intron. Default: 3 bases.
      - name: -spliceRegionIntronMax
        type: integer
        description: |
          Set maximum number of bases for splice site region within intron. Default: 8 bases.
      - name: -strict
        type: boolean_true
        description: Only use 'validated' transcripts (i.e. sequence has been checked).
      - name: -ud
        alternatives: [-upDownStreamLen]
        type: integer
        description: Set upstream downstream interval length (in bases).
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/staphb/snpeff:5.2a
    setup:
      - type: docker
        run: |
          touch ./var/software_versions.txt && \
          version=$(snpEff -version) && \
          version_trimmed=$(echo "$version" | awk '{print $1, $2}')
          echo "$version_trimmed" > ./var/software_versions.txt
runners:
  - type: executable
  - type: nextflow