functionality:
  name: bgzip
  description: Block compression/decompression utility
  info:
    homepage: https://www.htslib.org/
    documentation: https://www.htslib.org/doc/bgzip.html
    repository: https://github.com/samtools/htslib
    licence: MIT
  requirements:
    cpus: 1
    commands: [ bgzip ]
  arguments:
    - name: --input
      type: file
      direction: input
      description: file to be compressed or decompressed
      required: true
    - name: --output
      type: file
      direction: output
      description: compressed or decompressed output
      required: true
    - name: --decompress
      alternatives: -d
      type: boolean_true
      description: decompress the input file
  resources:
    - type: bash_script
      text: |
        [[ "$par_decompress" == "false" ]] && unset par_decompress
        bgzip -c \
          ${meta_cpus:+--threads "${meta_cpus}"} \
          ${par_decompress:+-d} \
          "$par_input" > "$par_output"
  test_resources:
    - type: bash_script
      text: |
        set -e

        "$meta_executable" --input "$meta_resources_dir/test_data/test.vcf" --output "test.vcf.gz"

        echo ">> Checking output of compressing"
        [ ! -f "test.vcf.gz" ] && echo "Output file test.vcf.gz does not exist" && exit 1

        "$meta_executable" --input "test.vcf.gz" --output "test.vcf" --decompress

        echo ">> Checking output of decompressing"
        [ ! -f "test.vcf" ] && echo "Output file test.vcf does not exist" && exit 1

        echo ">> Checking original and decompressed files are the same"
        set +e
        cmp --silent -- "$meta_resources_dir/test_data/test.vcf" "test.vcf"
        [ $? -ne 0 ] && echo "files are different" && exit 1
        set -e
        
        echo "> Test successful"
    - type: file
      path: test_data

platforms:
  - type: docker
    image: quay.io/biocontainers/htslib:1.19--h81da01d_0
    setup:
      - type: docker
        run: |
          bgzip -h | grep 'Version:' 2>&1 |  sed 's/Version:\s\(.*\)/arriba: "\1"/' > /var/software_versions.txt
  - type: nextflow