functionality:
  name: bgzip
  description: Block compression/decompression utility
  info:
    homepage: https://www.htslib.org/
    documentation: https://www.htslib.org/doc/bgzip.html
    repository: https://github.com/samtools/htslib
    licence: MIT
  requirements:
    cpus: 1
    commands: [ bgzip ]
  arguments:
    - name: --input
      type: file
      direction: input
      description: file to be compressed or decompressed
      required: true
    - name: --output
      type: file
      direction: output
      description: compressed or decompressed output
      required: true
    - name: --extra
      type: string
      description: extra arguments to pass to bgzip
      required: false
    - name: --threads
      type: integer
      description: number of threads to use
      required: false
      default: 1
  resources:
    - type: bash_script
      text: |
        bgzip -c "$par_extra" --threads "$par_threads" "$par_input" > "$par_output"
  test_resources:
    - type: bash_script
      text: |
        "$meta_executable" --input "$meta_resources_dir/test/test.vcf" --output "$meta_resources_dir/test.vcf.gz"
    - type: file
      path: test

platforms:
  - type: docker
    image: quay.io/biocontainers/htslib:1.19--h81da01d_0