name: agat_sp_complement_annotations
namespace: agat
description: |
    The script allows to complement a reference annotation with other annotations. 
    
      * A l1 feature from the addfile.gff that does not overlap a l1 feature from the reference annotation will be added. 
      * A l1 feature from the addfile.gff without a CDS that overlaps a l1 feature with a CDS from the reference annotation will be added. 
      * A l1 feature from the addfile.gff with a CDS that overlaps a l1 feature without a CDS from the reference annotation will be added. 
      * A l1 feature from the addfile.gff with a CDS that overlaps a l1 feature with a CDS from the reference annotation will be added only if the CDSs don't overlap. 
      * A l1 feature from the addfile.gff without a CDS that overlaps a l1 feature without a CDS from the reference annotation will be added only if none of the l3 features overlap. 
      
      ! It is sufficient that only one isoform is overlapping to prevent the whole gene (l1 feature) from the addfile.gff to be added in the output.
keywords: [gene annotations, GFF]
links:
  homepage: https://github.com/NBISweden/AGAT
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_complement_annotations.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references: 
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  - commands: [agat]
authors:
  - __merge__: /src/_authors/leila_paquay.yaml
    roles: [ author, maintainer ]
argument_groups:
  - name: Inputs
    arguments:
      - name: --ref
        alternatives: [-r, -i]
        description: Input GTF/GFF file used as reference.
        type: file
        required: true
        direction: input
        example: reference.gff
      - name: --add
        alternatives: [-a]
        description: |
          Annotation(s) file you would like to use to complement the
          reference annotation. You can specify as much file you want like.
          The order you provide these files matter. Once the reference file has been
          complemented by file1, this new annotation becomes the new
          reference that will be complemented by file2 etc. 
          So, be aware of what you want if you use several addfiles.
        type: file
        required: true
        direction: input
        multiple: true
        example: addfile1.gff
  - name: Outputs
    arguments:       
      - name: --output
        alternatives: [-o, --out, --outfile]
        description: Output gff3 containing the reference annotation with all the non-overlapping newly added genes from addfiles.gff.
        type: file
        direction: output
        required: true
        example: output.gff
  - name: Arguments
    arguments:
      - name: --size_min
        alternatives: [-s]
        description: |
          Option to keep the non-overlapping gene only if the CDS size (in
          nucleotide) is over the minimum size defined. Default = 0 that
          means all of them are kept.
        type: integer
        required: false
        example: 100
      - name: --config
        alternatives: [-c]
        description: |
          AGAT config file. By default AGAT takes the original agat_config.yaml shipped with AGAT. The `--config` option gives you the possibility to use your own AGAT config file (located elsewhere or named differently).
        type: file
        required: false
        example: custom_config.yaml
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/agat:1.4.0--pl5321hdfd78af_0
    setup:
      - type: docker
        run: |
          agat --version | sed 's/AGAT\s\(.*\)/agat: "\1"/' > /var/software_versions.txt
runners:
  - type: executable
  - type: nextflow