name: agat_sp_extract_attributes
namespace: agat
description: |
  The script takes a gtf/gff file as input. The script allows to extract
  choosen attributes of all or specific feature types. The 9th column of a
  gff/gtf file contains a list of attributes. An attribute (gff3) looks
  like that `tag=value`.
keywords: [gene annotations, GFF]
links:
  homepage: https://github.com/NBISweden/AGAT
  documentation: https://agat.readthedocs.io/en/latest/tools/agat_sp_extract_attributes.html
  issue_tracker: https://github.com/NBISweden/AGAT/issues
  repository: https://github.com/NBISweden/AGAT
references: 
  doi: 10.5281/zenodo.3552717
license: GPL-3.0
requirements:
  - commands: [agat]
authors:
  - __merge__: /src/_authors/leila_paquay.yaml
    roles: [ author, maintainer ]
argument_groups:
  - name: Inputs
    arguments:
      - name: --gff
        alternatives: [-f]
        description: Input GTF/GFF file.
        type: file
        required: true
        direction: input
        example: input.gff
      - name: --attribute
        alternatives: [--att, -a]
        description: |
          Attribute tag. The value of the attribute tag specified will be
          extracted from the feature type specified by the option `-p`.
        direction: input
        multiple: true
        type: string
        required: true
        example: protein_id
  - name: Outputs
    arguments:       
      - name: --output
        alternatives: [-o, --out, --outfile]
        description: Output GFF file. One file per attribute tag will be created using the attribute tag name as file name suffix.
        type: string
        required: true
        example: output.txt
  - name: Arguments
    arguments:
      - name: --primary_tag
        alternatives: [-p, -t, -l]
        description: |
          Primary tag option, case insensitive, list. Allow to specify the
          feature types that will be handled. 
          
          You can specify a specific feature by giving its primary tag name (column 3) as: 
            * cds
            * Gene
            * mRNA
          
          You can specify directly all the features of a particular
          level: 
          
            * level2=mRNA,ncRNA,tRNA,etc 
            * level3=CDS,exon,UTR,etc. 

          By default, all features are taken into account. Filling the option
          with the value "all" will have the same behavior.
        type: string
        required: false
        multiple: true
        example: gene
      - name: --merge
        alternatives: [-m]
        description: |
          By default, the values of each attribute tag are written in its
          dedicated file. To write the values of all tags in only one file,
          use this option.
        type: boolean_true
      - name: --dot
        alternatives: [-d]
        description: |
          By default, when an attribute is not found for a feature, a dot
          (.) is reported. If you don't want anything to be printed in such
          a case, use this option.
        type: boolean_true
      - name: --config
        alternatives: [-c]
        description: |
          AGAT config file. By default AGAT takes the original agat_config.yaml shipped with AGAT. The `--config` option gives you the possibility to use your own AGAT config file (located elsewhere or named differently).
        type: file
        required: false
        example: custom_config.yaml
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - type: file
    path: test_data
engines:
  - type: docker
    image: quay.io/biocontainers/agat:1.4.0--pl5321hdfd78af_0
    setup:
      - type: docker
        run: |
          agat --version | sed 's/AGAT\s\(.*\)/agat: "\1"/' > /var/software_versions.txt
runners:
  - type: executable
  - type: nextflow